-- FIND THE NUMBER OF HOSPITALS BY CITY AND THE SHARE FROM THE TOTAL AMOUNT OF HOSPITALS AS WELL

USE GeneralHospital;
GO
SELECT [HOSPITAL COUNTY], COUNT([Hospital ID]) AS [COUNT OF HOSPITALS], 
FORMAT(CAST(COUNT([Hospital ID]) AS FLOAT)/(SELECT COUNT([HOSPITAL ID]) FROM Hospitals),'P2') AS SHARE
FROM Hospitals H
GROUP BY [HOSPITAL COUNTY]
ORDER BY 1 ASC;

-- CALCULATE DISTANCE BETWEEN HOSPITALS
USE GeneralHospital;
GO
WITH T1 AS
(SELECT H1.[HOSPITAL ID] AS ID1,H1.[Hospital Longitude] AS LONG1,H1.[Hospital Latitude] AS LAT1, H2.[HOSPITAL ID] AS ID2,H2.[Hospital Longitude] AS LONG2,H2.[Hospital Latitude] AS LAT2
FROM Hospitals H1
JOIN Hospitals H2 ON H1.[Hospital ID]!=H2.[HOSPITAL ID])
,T2 AS
(SELECT ID1, CAST(LONG1 AS FLOAT) AS LONG1,CAST(LAT1 AS FLOAT) AS LAT1,ID2,CAST(LONG2 AS FLOAT) AS LONG2,CAST(LAT2 AS FLOAT) AS LAT2 
FROM T1)
,T3 AS 
(SELECT T2.*,POWER((POWER((LONG1-LONG2),2)+POWER((LAT1-LAT2),2)),0.5)*111 AS DISTANCE
FROM T2
WHERE ID1<ID2)
,T4 AS 
(SELECT T3.*, H1.[HOSPITAL CITY] AS ID1_CITY, H2.[HOSPITAL CITY] AS ID2_CITY
FROM T3
JOIN Hospitals H1 ON T3.ID1=H1.[HOSPITAL ID]
JOIN Hospitals H2 ON T3.ID2=H2.[HOSPITAL ID])
SELECT *
FROM T4
WHERE ID1_CITY!=ID2_CITY;

-- FIND PATIENTS WITH MOST ENCOUNTERS. FIND THEIR AGES
WITH T1 AS 
(SELECT [Master Patient ID],COUNT([Patient Encounter ID]) AS ENCOUNTER_COUNT
FROM Encounters
GROUP BY [Master Patient ID])
,T2 AS
(SELECT T1.[Master Patient ID],ENCOUNTER_COUNT,[Patient Name], [Patient Gender], CAST(REPLACE(REPLACE([Patient DOB],'/','-'),'YES','') AS DATE) AS [PATIENT DOB]
FROM T1
JOIN Patients P ON T1.[Master Patient ID]=P.[Master Patient ID])
SELECT T2.*, DATEDIFF(DAY,[PATIENT DOB],CAST(GETDATE() AS DATE))/365 AGE_NOW
FROM T2;



WITH T1 AS
(SELECT [Department ID],COUNT([Patient Encounter ID]) AS [NUMBER OF ENCOUNTERS]
FROM Encounters E
GROUP BY [Department ID])
SELECT [Hospital Name],[Department Name],[NUMBER OF ENCOUNTERS]
FROM T1 
JOIN Departments D ON T1.[Department ID]=D.[Department ID]
JOIN Hospitals H ON D.[Hospital ID]=H.[Hospital ID]
ORDER BY [Hospital Name], [NUMBER OF ENCOUNTERS] DESC;

-- CREATE A PROCEDURE TO FIND 5 CLOSEST HOSPITAL FOR THE PATIENT

USE GENERALHOSPITAL;
GO
DROP PROCEDURE IF EXISTS GET_DISTANCE;
GO
CREATE PROCEDURE GET_DISTANCE(@PATIENT_ID VARCHAR(55)) AS
BEGIN
	WITH P AS
	(SELECT [Master Patient ID],[Patient Longitude],[Patient Latitude]
	FROM Patients)
	, H AS
	(SELECT [Hospital ID], [Hospital Longitude], [Hospital Latitude]
	FROM Hospitals)
	,T1 AS
	(SELECT [Master Patient ID],
	CAST([Patient Longitude] AS FLOAT) AS [PATIENT LONGITUDE],
	CAST([Patient Latitude] AS FLOAT) AS [PATIENT LATITUDE],
	[Hospital ID],
	CAST([HOSPITAL Longitude] AS FLOAT) AS [HOSPITAL LONGITUDE],
	CAST([Hospital Latitude] AS FLOAT) AS [HOSPITAL LATITUDE]
	FROM H,P)
	, T2 AS
	(SELECT T1.*, POWER(POWER(([Patient Longitude]-[Hospital Longitude]),2)+POWER(([Patient Latitude]-[Hospital Latitude]),2),0.5)*111 AS DISTANCE
	FROM T1)
	, T3 AS
	(SELECT T2.*, ROW_NUMBER() OVER(PARTITION BY [MASTER PATIENT ID] ORDER BY DISTANCE ASC) AS [RANK]
	FROM T2)
	SELECT *
	FROM T3 
	WHERE [RANK]<=5 AND [Master Patient ID]=ISNULL(@PATIENT_ID,[Master Patient ID])
END;
GO
EXEC GET_DISTANCE @PATIENT_ID='100005';
--FIND MOST BUSY DAYS FOR THE HOSPITAL'S ADMISSION OFFICE

USE GeneralHospital;
GO
WITH T1 AS
(SELECT [Master Patient ID],
DATENAME(WEEKDAY,CAST(REPLACE(SUBSTRING([Patient Admission Datetime],1,CHARINDEX(' ',[Patient Admission Datetime])),'/','-') AS DATE)) AS [ADMISSION DAY]
FROM Encounters E)
SELECT [ADMISSION DAY],COUNT([Master Patient ID]) AS [ADMISSION COUNT],
FORMAT(CAST(COUNT([Master Patient ID]) AS FLOAT)/(SELECT COUNT([Master Patient ID]) FROM T1),'P2') AS PERCENTAGE
FROM T1
GROUP BY [ADMISSION DAY]
ORDER BY [ADMISSION COUNT] DESC;


--FIND IF TOTAL ACCOUNT CHARGE DIFFER FOR THE SAME HOSPITAL ACCOUNT IDs

WITH T1 AS
(SELECT [Hospital Account ID],COUNT([Hospital Account ID]) AS [COUNT]
FROM Accounts
GROUP BY [Hospital Account ID]
HAVING COUNT([Hospital Account ID])>1)
, T2 AS
(SELECT T1.[Hospital Account ID],[Total Account Charge $] --COLUMNS
FROM T1
JOIN Accounts A ON T1.[Hospital Account ID]=A.[Hospital Account ID])
, T3 AS
(SELECT T2.*, ROW_NUMBER() OVER(PARTITION BY [HOSPITAL ACCOUNT ID] ORDER BY [HOSPITAL ACCOUNT ID]) AS RN1
FROM T2)
, MAX_RN AS
(SELECT [Hospital Account ID], COUNT([Hospital Account ID]) AS MAX_RN
FROM T2
GROUP BY [Hospital Account ID])
,T4 AS
(SELECT T3.*, MAX_RN
FROM T3
LEFT JOIN MAX_RN M ON T3.[Hospital Account ID]=M.[Hospital Account ID])
,T5 AS
(SELECT T4.*, LAG([Total Account Charge $]) OVER(PARTITION BY [HOSPITAL ACCOUNT ID]ORDER BY [HOSPITAL ACCOUNT ID]) AS PREVIOUS
FROM T4)
SELECT T5.*
FROM T5
WHERE [Total Account Charge $]!=PREVIOUS AND PREVIOUS IS NOT NULL;


--FIND TOTAL CHARGE AND PAYED AMOUNTS FOR EACH PAYOR. FIND THE PERCENTAGE OF PAYEMENT OF THE TOTAL CHARGE AS WELL

USE GeneralHospital;
GO
SELECT [Primary Payor ID],FORMAT(SUM([Total Account Charge $]),'C2') AS CHARGE,FORMAT(-SUM([Total Account Payment $]),'C2') AS PAYMENTS,
FORMAT(SUM([Total Account Payment $])/SUM(-[Total Account Charge $]),'P2') AS [PERCENT PAYED OF TOTAL CHARGE]
FROM Accounts
WHERE [Primary Payor ID]!=''
GROUP BY [Primary Payor ID]
HAVING SUM([Total Account Charge $])!=0
ORDER BY SUM([Total Account Charge $]) DESC;


-- FIND MOST EXPENSIVE SURGICAL RESOURCES

SELECT [Surgical Resource Name],AVG([Surgical Resource Cost]) AS COST
FROM SurgicalCosts
GROUP BY [Surgical Resource Name]
HAVING COUNT([Surgical Resource Name])>10
ORDER BY 2 DESC;

